import "./globals.css";
import { ClientProvider } from "../utils/trpcClient";

export const metadata = {
  title: "Next13 tRPC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
