import "./globals.css";
import ProvidersWrapper from "../providers";
import Header from "./components/Header";

export const metadata = {
  title: "Next13 tRPC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ProvidersWrapper>
          <Header />
          {children}
        </ProvidersWrapper>
      </body>
    </html>
  );
}
